version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mxc-event-mssql-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 2G