@Mxc.EventManager.Api_HostAddress = http://localhost:5228

###

POST {{Mxc.EventManager.Api_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "email": "userlocalh@ostfff2",
  "password": "assword!"
}